### PR TITLE
Update issues template with no_template warning

### PR DESCRIPTION
**Pull request by rborn**
It seems that some people still don't use the template, so moved the warning on top and made it a little more aggressive :)

### CODE REVIEW

**Comment by rborn** [comment]
@alvelig @christopherdro 🐽

**Comment by christopherdro** [comment]
We could just make it a hard requirement and close all new issues that don't follow the template.
That Might be a bit too aggressive :)

**Comment by rborn** [comment]
For a while I'd close it manually, with a small message. 
But I thought the template should have the warning there.

**Comment by alvelig** [comment]
I don't feel like being much aggressive. The warning low priority without filled template nor reproducible example is fair enough.

**Comment by alvelig** [comment]
https://github.com/probot/stale?

**Comment by rborn** [comment]
@alvelig @christopherdro the stale bot looks good, I think we could give it a shot.

**Pull request merged**
