### PR TITLE
Merge Ground Overlay Support (PR-1586)

### PR DESCRIPTION
**Pull request by alvelig**
Replaces #1586, as after rebase to the current master.

### CODE REVIEW

**Comment by alvelig** [comment]
@isener mind checking my rebased PR? (BTW thank you very much)

**Comment by isener** [comment]
Good work mate, I don't have time to check fully. Will do it asap on the fly

**Comment by alvelig** [comment]
@rborn frankly speaking, no. I just checked that it was building ok. Did not check the features.

**Comment by rborn** [comment]
I'll merge and wait for the community feedback.

**Comment by tmaly1980** [comment]
React.PropTypes is deprecated. Every where else in this package we're using the separate package.

**Pull request merged**
