### PR TITLE
Fix https://github.com/react-community/react-native-maps/issues/2203

### PR DESCRIPTION
**Pull request by sytolk**
### Does any other open PR do the same thing?

no

### What issue is this PR fixing?

https://github.com/react-community/react-native-maps/issues/2203

### How did you test this PR?

every location is have timestamp and it's now received on RN side.

### CODE REVIEW

**Comment by rborn** [comment]
Please add the documentation too with platform specific  🤗
Can this be extended to iOS too? AppleMap and GoogleMap ?

Thank you

**Comment by sytolk** [comment]
@rborn I think that Documentation for onUserLocationChange exist: 
https://github.com/react-community/react-native-maps/blob/master/docs/mapview.md#events

 *Callback that is called when the underlying map figures our users current location (coordinate also includes isFromMockProvider value for Android API 18 and above). Make sure showsUserLocation is set to true and that the provider is "google"*

this is only minor change that add timestamp parameter to location object received on RN side and I don't think that that there is need documentation changes

**Comment by rborn** [comment]
@sytolk what about iOS ?

**Comment by sytolk** [comment]
sorry but I cannot test onUserLocationChange on iOS. But from documentation if the map provider is google and showsUserLocation is set to true should work.

**Comment by rborn** [comment]
LGTM @alvelig 🐽

**Pull request merged**
