### PR TITLE
Fix compile issues in Android (; expected and cannot find symbol)

### PR DESCRIPTION
**Pull request by jerolimov**
### Does any other open PR do the same thing?

No.

### What issue is this PR fixing?

Fixing a compile issue of the Android version. I did not understand exactly what the (merged) PR #2136 does, but it breaks the Android java build with this error(s):

```
AirMapUrlTileManager.java:50: error: ';' expected
    view.setMinimumZ(minimumZ)

# .. and after fixing this, also here:

AirMapUrlTile.java:32: error: cannot find symbol
      if(this.maximumZ && zoom > maximumZ) {
```

### How did you test this PR?

- Use the current master of react-native-maps (for example with `yarn upgrade react-native-maps@react-community/react-native-maps#master`)
- Build your android app with `react-native run-android`
- This fails with the error above. With this changes it compiles again.

### CODE REVIEW

**Comment by jerolimov** [comment]
ping @rborn and @akmjenkins, maybe you can check if the `minimumZ > 0` check is what you expect?

**Comment by pedrolopes10** [comment]
Hi, please merge this PR because master is not compiling in Android since 8 days ago!

**Comment by rborn** [comment]
@pedrolopes10 can you confirm you tested this PR and it compiles ok ?

**Comment by jerolimov** [comment]
Checkout the diff. It works and it fixes only obvious compiler issues.. 😉

**Comment by pedrolopes10** [comment]
@rborn sorry about the delay, yes I can confirm that it works fine.

Thanks for the merge and the great work!

**Pull request merged**
