### PR TITLE
Ground Overlay Support

### PR DESCRIPTION
**Pull request by isener**
For the iOS version; look here #1359
I tried and both environments works right now.

**NOTE: On iOS -> AirMaps does not support ground overlay fully. Use Google Maps on iOS.**

Android 
screenshot_1503495273
screenshot_1503495242

iOS
simulator screen shot 23 aug 2017 16 41 03
simulator screen shot 23 aug 2017 16 41 22

### CODE REVIEW

**Comment by isener** [comment]
Guy's for the iOS version; look here #1359
I tried and both environments works right now.

**NOTE: On iOS -> AirMaps does not support ground overlay fully. Use Google Maps on iOS.**

**Comment by noenthu** [comment]
Any chance you can add an example as part of the request?

**Comment by raihanrazi** [comment]
How do we make this work?

**Comment by aaronbuchanan** [comment]
How can we help move this issue towards a release?

**Comment by markmssd** [comment]
Willing to help as well. Tried it and i can confirm it works properly 👍

**Comment by markmssd** [comment]
Bump bump!

**Comment by alvelig** [comment]
@rborn 🐽  this and #1359 close #103

**Comment by alvelig** [comment]
Conflicts with localTile :(

**Comment by alvelig** [comment]
Conflicts with #1876

**Comment by rborn** [comment]
@alvelig mmm, can't they go along or they do the same stuff?

**Comment by alvelig** [comment]
Yep, they can. I see how to resolve it, but don't have much time to check if it works.

**Comment by rborn** [comment]
when you say "it conflicts?" it's functionality or git? because in git seems fine :|

**Comment by alvelig** [comment]
It was git. There was a merge conflict. Let me self assign this PR I'll take care tomorrow. I'm afraid we could loose something, I'll double check.

**Comment by alvelig** [comment]
Close (rebased and cleaned PR is #1918)

**Pull request closed without merging**
