### PR TITLE
Android polygon holes support

### PR DESCRIPTION
**Pull request by xeoh**
Support Android polygon holes.
Duplicated issue with #1271.

### CODE REVIEW

**Comment by rborn** [comment]
@alvelig  @christopherdro 🐽 what should we do with this, it seems to somehow replace #1271 which doesn't have any reply from the author.

LGTM

**Comment by alvelig** [comment]
Docs missing, but LGTM

**Comment by rborn** [comment]
@xeoh would you mind add docs? thnx 🤗

**Comment by xeoh** [comment]
@rborn ok

**Comment by xeoh** [comment]
Tell me if you want anything more on docs. Thks

**Comment by xeoh** [comment]
Tell me if you want anything more on docs. Thns

**Comment by alvelig** [comment]
That's it, thx!

**Pull request merged**
