### PR TITLE
Fixed issue where callout is presented behind markers on iOS

### PR DESCRIPTION
**Pull request by madapper**
(https://github.com/airbnb/react-native-maps/issues/1393)

### CODE REVIEW

**Comment by tpisto** [comment]
Unfortunately this is not fixing the issue where the markers are react views with numbers. Would be wonderful to solve this, since now it's kind of trouble for us. Can anyone give any pointers where to start to look at this - I can also spend some time to figure this out.

calloutunder

**Comment by madapper** [comment]
@tpisto Thank you for your feedback. I have looked further into this with the fix added and have replicated the error by implementing a clustering system that re adds new markers based on a bias. This doesn't always happen, but it happens in the same place each time. (Unfortunately, I got too excited that my fix fixed it!) 

The issue seems to be where the annotations are being added as subviews. See example below:

**Working:**
airmapmarker-good-map
airmapmarker-good-list

**Not Working:**
airmapmarker-bad-map
airmapmarker-bad-list

In the working example, the annotations are being added directly to the AirMap as annotation subviews. However, in the not working example, the annotation that is sitting over the top seems to have been added to an MKNewAnnotationContainerView, which is then added to the _MKMapContentView. There are two potential solutions to this that I can see on first glance:

1) Review the process for how the annotations are added. This could be a longer process in determining why the makers are being added in this way, but the general fix will be better in the long term.
2) Implement a workaround that will find the map view as a recursive function and shift the hierarchy around to suit the needs of the markers. This solution seems to be hacky and I am not sure it will work consistently. However, it is a quicker solution to implement if it works. 

I am happy to take a look at either option for its efficacy. But also throwing it out to the community if they have any thoughts that might improve the solutions.

**Comment by kirakik** [comment]
Any news on this being merged?

**Comment by xiaoTuiMao** [comment]
+1

**Comment by alizahid** [comment]
@madapper Another thing I noticed; if the callout is already open, and new markers are added and overlap, they will show above the callout. So maybe call `bringSubviewToFront` again after new makers are rendered?

**Comment by nbonamy** [comment]
+1

**Comment by markusguenther** [comment]
Please merge it. It is more or less a no brainer, so why not merge it?

**Comment by wwwemree** [comment]
+1

**Comment by cinder92** [comment]
this merge does not fix the issue

captura de pantalla 2017-10-23 a la s 18 06 24

**Comment by martsie** [comment]
+1 please merge this

**Comment by anandkumar144** [comment]
Still not working

**Comment by alvelig** [comment]
Does not fix. But I managed to find a workaround: https://github.com/airbnb/react-native-maps/issues/865#issuecomment-346980723

**Comment by olofd** [comment]
Did not work for me. Using this instead, works well : #1843

**Comment by alvelig** [comment]
@olofd Unfortunately, it did not work for me, as I am using supercluster and have markers that appear after callout is shown.  :(  And these appear above the callout. I'm struggling with the issue for a week, but I'm very weak at Objective C and MapKit :( Looks like these is due to the order of reactElements :(

**Comment by olofd** [comment]
@alvelig. Ah. Ok. I’ll see if I can make it work for markers that appear when a callout is open.

**Comment by alvelig** [comment]
Look, my approach was to add callout as a new annotation to the end of the stack. Calling `mapview:addAnnotation:` for a newly allocated MKPointAnnotation with self coordinates and initializing PinView resulted in the pinView appear behind the current marker.

**Comment by olofd** [comment]
@alvelig send a small code example of what you’re doing or that demonstrates your issue!

**Comment by alvelig** [comment]
@olofd need your help. It looks like I found the way to solution. 

I noticed that the callout is in MKNewAnnotationContainer, but the markers above it are direct children of AirMaps, added in AirMaps.m:
```
- (void)insertReactSubview:(id<RCTComponent>)subview atIndex:(NSInteger)atIndex {
...
    [_reactSubviews insertObject:(UIView *)subview atIndex:(NSUInteger) atIndex];
}
```
Commenting that line all annotations appear in MKNewAnnotationContainer and the callout is before all the markers.

Of course, this is only a way to go, as `_reactSubviews` array is used to detect removed elements if markers change in React. But it looks like I found a way to go and correctly deal with this undocumented feature 🤣

**Comment by alvelig** [comment]
Eureka: https://github.com/airbnb/react-native-maps/issues/1844:

Just override `- (void)addSubview:(UIView *)view` in AirMap.m:

```
- (void)addSubview:(UIView *)view {
    if([view isKindOfClass:[AIRMapMarker class]]) {
        [self addAnnotation:(id <MKAnnotation>)view];
    } else {
        [super addSubview:view];
    }
}
```

**Comment by alvelig** [comment]
#1845 should solve this problem. Please comment if you tested and if there are any bugs detected, as collaborators ask me to have positive replies on my pull request to merge it to master.

**Comment by alvelig** [comment]
This does not solve the problem. Follow #418

**Pull request closed without merging**
