### PR TITLE
Fix custom marker updates on android #1611 #2048

### PR DESCRIPTION
**Pull request by fqborges**
### Does any other open PR do the same thing?
No

### What issue is this PR fixing?
On Android, using Google Maps, markers with custom views/images are not being updated correctly when other properties are changed (mainly coordinates). Sometimes markers are not draw anymore, until the child view/image is changed.

#1611 and #2048 are related.

### How did you test this PR?

1. Create a simple app with a MapView and 3 or more markers that have distinct views for normal/selected states with distinct sizes.
2. After MapView first rendered, dispatch changes to the markers coordinates and selected state (use a timer, button or marker touch event).
3. Expect markers to not update or disappear from map after a couple of changes.
4. Apply this patch and markers update as expected.

- Which platform/api: Android & Google
- Did you test this on a real device, or in a simulator? Simulator and Real device

### CODE REVIEW

**Comment by rborn** [comment]
LGTM @alvelig 🐽

**Comment by alvelig** [comment]
@fqborges Wow! So the problem was just `new MarkerOptions()` that were empty in certain situations?

**Comment by fqborges** [comment]
@alvelig Actually not empty, just outdated. And there was a chance of the outdated referenced bitmaps getting collected and not being valid for drawing anymore.

I found that in certain updates the markers are added then removed from map, instead of just get the properties updated. In this cases, the marker options used are the original created, with the initial values.

**Comment by alvelig** [comment]
Great job. I'll test and maybe close even more issues. Thank you!

**Pull request merged**
