### PR TITLE
Updates to build.gradle

### PR DESCRIPTION
**Pull request by bsmarimon**
Was wondering if it'd be possible to update the sdkVersions and buildToolsVersions used in the android side of the project. In my experience so far, the newer versions of gradle (3.0) require the versions to be at least 26.

### CODE REVIEW

**Comment by calvinlsliang** [comment]
Yes! This is sorely needed.

**Comment by rborn** [comment]
LGTM @alvelig 🐽

**Comment by christocracy** [comment]
Here's a [better idea](https://github.com/transistorsoft/react-native-background-fetch/wiki/Solving-Android-Gradle-Conflicts).  Simply check for gradle properties defined in one's root `build.gradle`, as recommended by [Android Gradle Tips & Tricks](https://developer.android.com/studio/build/gradle-tips.html)

**Comment by alvelig** [comment]
@bsmarimon Why don't we step to 27 right away?

@christocracy so you advice against upgrading?

@rborn sorry, was very busy last week.

**Comment by alvelig** [comment]
I think we'll close that in favor of #2047, don't you mind, @bsmarimon?

**Comment by christocracy** [comment]
@alvelig see #2047.  With this PR, you won't need to rely on `react-native-maps` "Updating to 27 right away".  It will become a slave to *your* desired version whenever you want.

**Comment by alvelig** [comment]
@christocracy Yes, I've already seen that and I agree totally

**Comment by rborn** [comment]
Closing in favour of #2047 

@bsmarimon thanks for your PR 🤗

**Pull request closed without merging**
