### PR TITLE
 Add openning the .xcworkspace file instead of .xcodeproj to documentation

### PR DESCRIPTION
**Pull request by mrabedini**
An emphasis to open .xcworkspace instead of .xcodeproj was added to documentation.

### CODE REVIEW

**Comment by rborn** [comment]
@mrabedini thank you! 🤗

**Comment by theideasaler** [comment]
Hi @rborn  @mrabedini ,
If I want to install other libraries into my react native project manually in the future, should I install them in .xcodeproject or in .xcworkshop file?

Thanks,
Neo

**Comment by rborn** [comment]
@theideasaler as long as you have any pods in the app you need to use the `.workspace`

**Comment by theideasaler** [comment]
thanks

**Pull request merged**
