### PR TITLE
Create template for PR

### PR DESCRIPTION
**Pull request by rborn**

### CODE REVIEW

**Comment by rborn** [comment]
@alvelig 🐽

**Comment by alvelig** [comment]
LGTM!

**Comment by rborn** [comment]
@alvelig could you merge it so we have it in place please 🤗

**Comment by lachenmayer** [comment]
This template is a great idea, thanks for this!

Could I suggest adding a section called "How did you test this PR?" or similar - it would be great to stimulate people to write a test plan, even if it is super basic.

**Comment by rborn** [comment]
@lachenmayer fancy a PR? 😹

**Comment by lachenmayer** [comment]
@rborn sure :) https://github.com/react-community/react-native-maps/pull/2097

**Pull request merged**
