### PR TITLE
Move babel-plugin-module-resolver and babel-preset-react-native to devDependencies

### PR DESCRIPTION
**Pull request by jmheik**
### Does any other open PR do the same thing?
No.

### What issue is this PR fixing?

Babel-plugin-module-resolver and babel-preset-react-native are included as runtime dependencies. As far as I can see they are only referred from .babelrc which is also in .npmignore, so they are not used by end users who install react-native-maps as npm module. However, these deps have quite a lot of transitive dependencies. This PR moves them to devDependencies to spare end users from downloading them and bloating the node_modules.

### How did you test this PR?

I have searched the code base, and not found any other use for these two deps than .babelrc, which is excluded from npm published version.

### CODE REVIEW

**Comment by jmheik** [comment]
What do you think @rborn @alvelig ? This would help cleaning up quite some transitive deps from people's projects as can be seen here https://npm.anvaka.com/#/view/2d/react-native-maps

**Comment by alvelig** [comment]
I like your idea, @jmheik. @rborn, what do you think?

**Comment by todorone** [comment]
These type of dependencies are for sure not suitable for `dependencies` section.
@rborn Please look if this PR can be merged.

**Comment by rborn** [comment]
@todorone done, can you add it to the 0.22.1 changelog? 🤗

**Comment by rborn** [comment]
@jmheik ❤️

**Pull request merged**
