### PR TITLE
fix module undefined bug in react-native@0.54.0 (#2051)

### PR DESCRIPTION
**Pull request by hrl7**

### CODE REVIEW

**Comment by bramus** [comment]
Nice one, thanks!

@alvelig Can a new version (0.20.2? 0.21.0?) of `react-native-maps` be released? Because right now 0.20.1 isn't working with RN 0.54.0. This merged PR fixes it.

**Comment by alvelig** [comment]
@christopherdro 🐽

**Comment by bramus** [comment]
You might want to wait with that new version … i've come to notice that the current master doesn't play nice with Android. See https://github.com/react-community/react-native-maps/issues/2058

**Comment by ibrahimab** [comment]
@hrl7 awesome! thank you for your contribution 👍 

@bramus Is there a date for the new version? Do you need any help?

**Comment by phillbaker** [comment]
Looks like #2058 has been fixed, any update on releasing a version with this fix?

**Comment by Arshiamidos** [comment]
#2051
check this out

**Pull request merged**
