### PR TITLE
Added tracksViewChanges description to marker docs

### PR DESCRIPTION
**Pull request by satori-ytolstoguzov**
Also added default values for the props I recognized.

### CODE REVIEW

**Comment by rborn** [comment]
@satori-ytolstoguzov is this related to #1969? If yes maybe you could merge it with that PR?
Thanks

**Comment by satori-ytolstoguzov** [comment]
@rborn They are not related to each other as far as I understand. This PR adds documentation for existing feature of react-native-maps, when #1969 adds new feature, although similar.

**Comment by alvelig** [comment]
LGTM. Thank you for paying attention to such details

**Comment by rborn** [comment]
Travis please

**Comment by rborn** [comment]
@satori-ytolstoguzov sorry, I merged the previous PR and we need to fix the conflicts now, could you please have a look?  🤗

**Comment by satori-ytolstoguzov** [comment]
@rborn That's actually good. I noticed couple of inconsistencies between `tracksViewChanges` and `tracksInfoWindowChanges` documentation. Rebased and fixed it

**Pull request merged**
