### PR TITLE
Add native animation for Markers on Android (with documentation)

### PR DESCRIPTION
**Pull request by BEGEMOT9I**
This is a copy of [#1782](https://github.com/react-community/react-native-maps/pull/1782) with documentation.

### CODE REVIEW

**Comment by rborn** [comment]
LGTM 
@alvelig 🐽

**Comment by alvelig** [comment]
Please update the example as well https://github.com/react-community/react-native-maps/blob/master/example/examples/AnimatedMarkers.js

Спасибо!

**Comment by rborn** [comment]
@BEGEMOT9I could you please fix the things travis is complaining ? 🤗

**Comment by rborn** [comment]
LGTM @alvelig 🐽

**Comment by alvelig** [comment]
Great! LGTM

**Comment by henninghall** [comment]
Great improvement! What about iOS, is it already using native drivers for marker animations?

**Pull request merged**
