### PR TITLE
[0.22.0] Release

### PR DESCRIPTION
**Pull request by todorone**

### CODE REVIEW

**Comment by ravirajn22** [comment]
@rborn @alvelig Pls look into this. Thanks

**Comment by rborn** [comment]
@christopherdro 🐽 can we get a release?

**Comment by christopherdro** [comment]
@todorone Thanks for putting this together!
Could you update the versions in the Podfile.lock and gradle.properties as well?

See https://github.com/react-community/react-native-maps/pull/2146/

**Comment by todorone** [comment]
@christopherdro Did it. Please check if done correctly.

**Comment by todorone** [comment]
@christopherdro Is there anything more required from my side to proceed with the release?

**Comment by rborn** [comment]
@todorone can we add https://github.com/react-community/react-native-maps/commit/a45f7a74ed138deb616b6081b4ea5f9355e29710 to the change-log please?

@christopherdro 🐽 publish ? 😍

**Comment by todorone** [comment]
@rborn @christopherdro  Done.

**Comment by rborn** [comment]
@christopherdro  🙀🎉❤️

**Pull request merged**
