### PR TITLE
minSDK in manifest errors the compilation. Fixed

### PR DESCRIPTION
**Pull request by dkfl1995**
No.

### What issue is this PR fixing?

#2471

### How did you test this PR?

Yes. I tried to recompile project on Android Studio with applied commit. (The steps are described in issue numbered above)

### CODE REVIEW

**Comment by tigranbalayan** [comment]
Can You please merge this PR and release new version?

**Comment by rborn** [comment]
@dkfl1995 how does this influence older sdks with older gradle? 🤗

**Comment by dkfl1995** [comment]
It doesn't harm older sdks at all. I had been left minSDK version as it was earlier so, it couldn't let older sdks be broken

**Comment by rborn** [comment]
LGTM @alvelig 🐽

**Pull request merged**
