### PR TITLE
Add support for polygons with holes for Google Maps on Android

### PR DESCRIPTION
**Pull request by pjaraherrera**
Add support for create polygons with holes for Google Maps on Android. 

screenshot_1493171197

### CODE REVIEW

**Comment by aaronbuchanan** [comment]
@nornak thanks for working on this!! Any plans to implement @ericapply's suggestions above? Would like to use this (without maintaining a fork!)

**Comment by aaronbuchanan** [comment]
Still looking forward to this one making it's way into a release!

**Comment by aaronbuchanan** [comment]
Anyone know *if/when* this will get merged

**Comment by aaronbuchanan** [comment]
I found a problem when a polygon does NOT have holes, this fixed it:
```
    if (holes != null) {
      for (int i = 0; i < holes.size(); i++) {
        options.addHole(holes.get(i));
      }
    }
```

**Comment by rborn** [comment]
Closing in favor of #1781
@pjaraherrera ping me if you think there are any issues 🤗

**Pull request closed without merging**
