### PR TITLE
Adding overlaying components details

### PR DESCRIPTION
**Pull request by SKempin**
How to overlay other React components on top of the `MapView`. This was not clear from the documentation and took some research to find a solution.

### Does any other open PR do the same thing?

No, this is to make it clear in the documentation.

### What issue is this PR fixing?

Documentation for overlaying components on the MapView

### How did you test this PR?

I found multiple other repos that utilise the same approach.

### CODE REVIEW

**Comment by marcoautiero** [comment]
Well, to me it's still not clear... I mean, I tried
```
<MapView  
                            style={{
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
    }}
                            initialRegion={{
                                latitude: 37.78825,
                                longitude: -122.4324,
                                latitudeDelta: 0.0922,
                                longitudeDelta: 0.0421,
                            }}
                            <View style={{zIndex: 4, position: "absolute", height:400, widht:400, background: '#0000ff', bottom: 50}}></View>
                        </MapView>
```
but I don't see any trace om `<View/>` that is supposed to be in overlay on the map.

**Comment by rborn** [comment]
@marcoautiero you cannot "embed" a View in a Map. If you want to show something `ontop` of the map just treat it like any other component.

```
<MapView  style={{position: 'absolute', top: 0,left: 0,right: 0,bottom: 0}} initialRegion={{ latitude: 37.78825, longitude: -122.4324, latitudeDelta: 0.0922, longitudeDelta: 0.0421}}></MapView>

<View style={{zIndex: 4, position: "absolute", height:400, widht:400, background: '#0000ff', bottom: 50}}></View>
```

**Comment by marcoautiero** [comment]
Oh i see, in this case of course the content in overlay is static and doesn't follow the events happening in the map (scaling, panning and so on)...big limit for me.

Thank you for your reply anyway.

**Comment by rborn** [comment]
@marcoautiero in this case you need to check `Overlay` there is an example in the repo on how to create custom overlays

**Pull request merged**
