### PR TITLE
add ios default-map support overlay images (merge chocky335's branch and add iOS GoogleMaps support)

### PR DESCRIPTION
**Pull request by smellman**
I open new PR with bug fix https://github.com/airbnb/react-native-maps/pull/1279 .
Original PR is https://github.com/airbnb/react-native-maps/pull/1140 .

- supports overlay images both iOS MapKit and GoogleMaps.
- fix mirrored presentation of image bug in MapKit.
- ready to merge current master

Also it have this bug in MapKit:

- Show image just after tap screen, swipe, scale...

### CODE REVIEW

**Comment by henrikra** [comment]
Can you give example screenshot of this?

**Comment by smellman** [comment]
@henrikra Please check following screenshots:
Screenshot on iOS Mapkit
Screenshot on iOS GoogleMaps

**Comment by henrikra** [comment]
So what is the advantage of this compared to `Marker`?

**Comment by smellman** [comment]
This component can draw image with same bounds in any zoom level.

for example, zoom out: 



and zoom in:



And someone want to this component: https://github.com/airbnb/react-native-maps/issues/868, https://github.com/airbnb/react-native-maps/issues/400, https://github.com/airbnb/react-native-maps/issues/1212

**Comment by smellman** [comment]
Also it supports rotation:

**Comment by henrikra** [comment]
Wow interesting. What is some nice use case as an example? :D

**Comment by smellman** [comment]
This is like Leaflet's L.ImageOverlay.
Nice use case is overlay old map image like this: http://bl.ocks.org/michellechandra/a5c9565214564f68135c

I try this example in react-native-maps.



In this case, I download image locally, but I can use same parameter to set bounds.

**Comment by derek-young** [comment]
Hey henrikra, here's another use-case for this: I am building an application that allows festival goers to view their location relative to the festival map. The festival map is overlaid on Google Maps using this ImageOverlay functionality, and the user's maker/position is overlaid on the festival map. 

Attached is a screenshot. I'd love to see this functionality implemented in React Native. 

Thanks!

screen shot 2017-06-10 at 1 11 16 pm

**Comment by isener** [comment]
Which feature do you used for overlay? I don't understand though

**Comment by isener** [comment]
I also want this feature as official map feature 👍

**Comment by isener** [comment]
I tried it works but there is a small bug (guess) on it. When I put an other elements such as Polyline and Marker, image shown as cropped. I tried a lot, it's not a loading error. When I don'tt put any other elements over on it, it works successfully. Any idea?

screenshot at jun 17 07-30-46

**Comment by markmssd** [comment]
@isener Are you trying it on the simulator, or on an actual device? When I was using UrlTile on the Simulator, I had the same problem, but on the iPhone it works perfectly... worth a try!

**Comment by isener** [comment]
@markmssd Also tried both on Simulator and iPhone 5s device. Same result. May be any other bug caused it happen.

**Comment by isener** [comment]
By the way is it possible to us in Android? Can we implement AirMaps functions on .java? Or do we have any other option to make it possible? @smellman

**Comment by smellman** [comment]
@isener It may possible in Android with GroundOverlay.
https://developers.google.com/maps/documentation/android-api/groundoverlay?hl=en
Sorry, I'm busy my work and getting ready for State of the Map 2017. I will make the time after SOTM.

**Comment by Dtraft** [comment]
+1 For this issue - Looks like there is only a minor merge conflict.  Would love to overlay NOAA radar images e.g. https://radar.weather.gov/radar.php?rid=BOX (Raw image here: http://radar.weather.gov/ridge/Conus/RadarImg/northeast_radaronly.gif)

Anything I can do to help here?

**Comment by raihanrazi** [comment]
How are we able to use this?

**Comment by smellman** [comment]
Today, I rewrite fix all code for current master and I merge #1586 by hand and hack it.

- merge PR #1718 
- support fetch image from internet
- update to new React code (prop-types, React.Component)
- merge PR #1586 and fix to support bundle image and fetch image from internet

**Comment by smellman** [comment]
I just fix document and un-comment for local test.

**Comment by smellman** [comment]
I want to change ISupportImageReader.java to another name because the name is ugly.
This interface to need to support ImageReader.
I plan refactoring AirMapMarker to use ImageReader because AirMapMarker and AirMapOverlay can share same code.
Does anyone have any ideas or advice?

**Comment by MartynasZilinskas** [comment]
Any progress?

**Comment by MartynasZilinskas** [comment]
@smellman Worst case scenario it will be changed in following PR. Anyway it's not for me to decide. I am just really looking forward to this feature.

**Comment by rborn** [comment]
@smellman what is that file doing? :) maybe we can find a batter name

**Comment by isener** [comment]
Don't PR this one, it's already merged on master as you see there;
https://github.com/react-community/react-native-maps/pull/1918

**Comment by rborn** [comment]
@isener so could you confirm that the one you said it's merged contains this PR?
If yes I'll just close this one to avoid more confusion.

**Comment by rborn** [comment]
@smellman I will close this one, maybe you could collaborate with @isener for further improvements :) Thanks a lot for the PR 🤗
@MartynasZilinskas let us know if you have questions.

**Comment by MartynasZilinskas** [comment]
@rborn I haven't noticed that new feature was merged recently. I will try it out. 👍

**Comment by rborn** [comment]
@MartynasZilinskas not sure is on npm, so you might need to use the git version

**Comment by MartynasZilinskas** [comment]
@smellman Could you ping me when you make a new pr?

**Comment by CQCumbers** [comment]
The master branch for react-native-maps still does not appear to have iOS support for ground overlays, as I get 'Native component for "AirMapOverlay" does not exist' errors when using MapView.Overlay on iOS. Is someone currently working on adding iOS ground overlay support? Is it likely to be added within a few weeks? Is there something I can do to help?

**Comment by Gloix** [comment]
Rotation didn't make it to #1918. 🙁 @smellman @isener

**Comment by tristanwagner** [comment]
> I tried it works but there is a small bug (guess) on it. When I put an other elements such as Polyline and Marker, image shown as cropped. I tried a lot, it's not a loading error. When I don'tt put any other elements over on it, it works successfully. Any idea?
> 
> screenshot at jun 17 07-30-46

@isener @smellman  Hello, I'm having the same issue where the Overlay is cropped when you zoom in and there is markers on top of it. Did you found any workaround about this bug ? Thanks

**Comment by NotTooReact89** [comment]
I have a 1.2mb image which I need to add as an overlay. When I tried th example with my image, it does not load. Would you happen to know if there is a limit on the image size?

**Pull request closed without merging**
