### PR TITLE
fix fitToSuppliedMarkers function

### PR DESCRIPTION
**Pull request by marcelkalveram**
Fixes https://github.com/react-community/react-native-maps/issues/2513

### Does any other open PR do the same thing?

https://github.com/react-community/react-native-maps/pull/2520

seems to fix the same issue

### What issue is this PR fixing?

https://github.com/react-community/react-native-maps/issues/2513

### How did you test this PR?

iOS simulator. Builds were failing without this fix.

### CODE REVIEW

**Comment by marcelkalveram** [comment]
btw: the bug got originally introduced here: https://github.com/react-community/react-native-maps/pull/2479

**Comment by rborn** [comment]
@marcelkalveram do we need to adjust docs too?

**Comment by marcelkalveram** [comment]
@rborn this doesn't work with Apple Maps (only Google, both Android and iOS), as mentioned in my previous PR. Not sure if this is something that should be mentioned in the docs? At least, after this PR, it shouldn't fail anymore with Apple Maps.

**Comment by rborn** [comment]
We should mention that it only works with google maps or we'll get a lot of issues reported (it will be, trust me). 
So if the docs need to be amended please do so and I'll merge asap.
Thank you ❤️

**Comment by rborn** [comment]
@marcelkalveram I'll merge this

**Pull request merged**
