### PR TITLE
Fix for pointForCoordinate and coordinateForPoint

### PR DESCRIPTION
**Pull request by wasedaigo**
* Fixed typo "coordinateFromPoint"
* Moved coordinateForPoint/pointForCoordinate from AirMap to AirMapManager
* Fixed how resolve/reject are handled

I have tested on iOS. Yet not confirmed on Android. If anybody can confirm this works on Android, I think this PR is good to go.

### CODE REVIEW

**Comment by rborn** [comment]
LGTM @alvelig 🐽
PS - not tested on android yet

**Comment by rborn** [comment]
@wasedaigo does it work on iOs for both Apple maps and Google maps ?
also how's compared to this:  https://github.com/react-community/react-native-maps/pull/1737

🤗

**Comment by wasedaigo** [comment]
@rborn I haven't tested GoogleMap, but it seems it won't work. Sounds like we can integrate part of #1737 to make it work. What would be the best approach here? I is hard to ask everybody to test all combinations

**Comment by rborn** [comment]
@wasedaigo @alvelig  I will try to test on android tomorrow and also if we can merge first #1737 and then this one.
If problems arise we might wanna integrate that PR in yours. OR if you know for sure that will be problems you could try to integrate it and update the PR. And I'll test.

Works for you?

**Comment by wasedaigo** [comment]
actually #1737 should be closed, the implementation for GoogleMap is already there.
It is just this commit https://github.com/react-community/react-native-maps/commit/9cb22b9dd8249169cddaf94903a64e6602b460e0 made a mistake on iOS AppleMap part

**Comment by wasedaigo** [comment]
@rborn is everything alright? I want to make sure I am not blocking you

**Comment by rborn** [comment]
@wasedaigo sorry, didn't have the time to look into and the next days I'll be very busy. I'll try to take a look in the  next evenings but I don't promise 😔

**Comment by rborn** [comment]
@wasedaigo it works great on android ❤️

Sorry for the delay.

**Comment by henninghall** [comment]
I found some issues related to this pull request. 
1. coordinateForPoint with Google maps does not work on iOS
2. coordinateForPoint resolves coordinate on format {lat, lng} on iOS with apple maps and {latitude,longitude} with google maps on android.

**Comment by rborn** [comment]
@wasedaigo can you have a look at this ?

**Pull request merged**
