### PR TITLE
Fix annotations added directly to AirMap view as subviews

### PR DESCRIPTION
**Pull request by alvelig**
Adapts RTCUIView+React lifecycle to MapKit API, when adding annotations (AirMapMarker).

Fixes:
https://github.com/airbnb/react-native-maps/issues/1844
https://github.com/airbnb/react-native-maps/pull/1405
https://github.com/airbnb/react-native-maps/issues/1393
https://github.com/airbnb/react-native-maps/issues/983
https://github.com/airbnb/react-native-maps/issues/865
https://github.com/airbnb/react-native-maps/pull/806
https://github.com/airbnb/react-native-maps/issues/751
https://github.com/airbnb/react-native-maps/issues/662
https://github.com/airbnb/react-native-maps/issues/553
#777, #561, #418, #314

Probably: 
https://github.com/airbnb/react-native-maps/issues/891

### CODE REVIEW

**Comment by olofd** [comment]
This works fine, but testing out here, it messes with the animation created in SMCalloutView. Did you notice?

**Comment by alvelig** [comment]
No I did not notice any problems. Actually there should not be any, as my fix complies with the MapKit API. Could you attach a gif or a video of the problem. Maybe I can see 
There's another naughty bug, that Callout sometimes hides after is shown. They might be related.

**Comment by alvelig** [comment]
@christopherdro what are requirements to merge? Or any comments on that code?
I believe that this implementation is a correct one according to the MapKit API. Would you mind to merge this PR?

**Comment by christopherdro** [comment]
@alvelig Thanks for the PR! Could you possibly comment inside the issues you linked requested some others to test your solution?

**Comment by i8wu** [comment]
@alvelig any idea for a fix on android as well?

**Comment by alvelig** [comment]
@i8wu Do you experience it on Android as well? I did not have this it on Android.
Did it work for you in iOS?

**Comment by tpisto** [comment]
Thank you for your work!
Should this work with default iOS pins? I implemented this code to AirMaps project and callout appears still behind default iOS markers...
screen shot 2017-12-08 at 14 08 35

**Comment by tpisto** [comment]
I can instead confirm that this works:

**Comment by alvelig** [comment]
I tested it only with image markers. I'll review.

**Pull request closed without merging**
