### PR TITLE
removed BatchedBridge from docs/installation.md

### PR DESCRIPTION
**Pull request by vinicius5581**
### Is there any other PR opened that does the same ?
No

### What issue is this PR fixing

Installation error on the `pod install` step with the current PodFile on the docs/installation.md

https://github.com/react-community/react-native-maps/issues/2063

### CODE REVIEW

**Comment by vinicius5581** [comment]
This solves the original issue with the `pod install` error but as pointed out on the ticket I haven't been able to run `react-native-maps` <MapView /> component yet after a following

**Comment by vinicius5581** [comment]
I can now run my app with "react-native-maps" after updating my package.json to start pulling "react-native-maps" directly from github.

"react-native-maps": "github:react-community/react-native-maps"

**Comment by rborn** [comment]
@vinicius5581 great stuff, could you please also update the `react-native-maps/example/ios/Podfile` file and test if it runs too? 

Thank you 🤗

**Comment by rborn** [comment]
@vinicius5581 I updated your PR so we can merge, sorry for this 🤗

@alvelig 🐽

**Comment by vinicius5581** [comment]
@rborn LGTM!

**Pull request merged**
