### PR TITLE
MapOverlay support on ios and android

### PR DESCRIPTION
**Pull request by srikanthkyatham**
Adding ios google maps support

Adding android support

### CODE REVIEW

**Comment by srikanthkyatham** [comment]
Hello everyone,

I should have checked there are already few pending PRs with same implementation.
I think this PR, if I am right then only this PR supports all the platforms in one. 
It's been a good learning experience with the MapKit and Google Maps.

Please comment on this. If I need to continue working or not. Appreciate your time.
This is my first big contribution to a major project in Open Source. Looking forward for feedback.

**Comment by srikanthkyatham** [comment]
Any update on this pull-request

**Comment by markmssd** [comment]
I think there's other similar pull requests, would love to see them merged.
GJ @srikanthkyatham

**Comment by alvelig** [comment]
@rborn @christopherdro  Don't we have this functionality already merged, do we?

**Comment by rborn** [comment]
@alvelig I think we do :|

**Comment by g3r4n** [comment]
I think since #2022 all the platform are supporting Overlay. @rborn should we close this one ?

**Comment by rborn** [comment]
@srikanthkyatham thanks a lot for your PR 🤗
Somehow there were other PRs with the same funcionality pushed so I had to close this.

**Pull request closed without merging**
