### PR TITLE
zIndex doesn't work when the map moves in iOS 11

### PR DESCRIPTION
**Pull request by dahiri-farid**
### Does any other open PR do the same thing?

Don't think so. This is an open issue.

### What issue is this PR fixing?

https://github.com/react-community/react-native-maps/issues/1671

### How did you test this PR?

I have tested my changes on iOS Simulators (iOS 11 and iOS 10)

### CODE REVIEW

**Comment by rborn** [comment]
@alvelig 🐽 LGTM

**Comment by alvelig** [comment]
LGTM 👍

**Comment by dahiri-farid** [comment]
Cool, thanks

**Comment by ppatel890** [comment]
Any timeline on publishing these changes to npm?

**Comment by sleeviin** [comment]
it's not working yet, it improves a lot, but still it has sometimes where if you toggle between markers it doesn't work properly.

try adding a lot of markers and set one with more zindex than the rest, and touch all the near markers with the one and zoom out, you'll see all touched items will overlap that one

**Pull request merged**
