### PR TITLE
[iOS Google Maps] Added support of lineDashPattern polyline props to iOS Google Maps

### PR DESCRIPTION
**Pull request by satori-ytolstoguzov**
### Does any other open PR do the same thing?
No

### What issue is this PR fixing?

#1387

### How did you test this PR?

https://github.com/satori-ytolstoguzov/rn-maps-callout-offset/tree/dashed-polylines

```
                    <MapView.Polyline coordinates={[
                        {latitude: 37.88045, longitude: -122.3903},
                        {latitude: 37.78825, longitude: -122.4324},
                        ]}
                                      lineDashPattern={[30, 30]}
                    />

                    <MapView.Polyline coordinates={[
                        {latitude: 37.88045, longitude: -122.4324},
                        {latitude: 37.78825, longitude: -122.3903},
                    ]}
                                      lineDashPattern={[30, 30, 15, 30]}
                    />
```

simulator screen shot - iphone 8 plus - 2018-05-07 at 15 17 53

### CODE REVIEW

**Comment by satori-ytolstoguzov** [comment]
@rborn My colleague've implemented similar same thing for android. I think he will prepare PR soon.

The documentation isn't needed an update for this one, because it was wrong before, claiming that iOS support it, instead of only Apple Maps. With this PR both iOS map implementation support it, so documentation is correct once again.

**Comment by rborn** [comment]
@alvelig 🐽

**Comment by alvelig** [comment]
LGTM

**Comment by filipef101** [comment]
https://github.com/react-community/react-native-maps/pull/2257

**Pull request merged**
