### PR TITLE
Manage Zoom Controls visibility on the map 

### PR DESCRIPTION
**Pull request by timotew**
Manage Map Zoom controls, Disabling `zoom` and `zoom controls` can also be used to disable `double tap` zoom gesture as suggested in  #1133

### CODE REVIEW

**Comment by timotew** [comment]
@lelandrichardson Hi there! How should we proceed on this PR?

**Comment by timotew** [comment]
@rborn how are we to handle this `Good First PR`.

**Comment by rborn** [comment]
@timotew I'm a little overloaded right now, I'll review as soon as I have some spare time 🤗
Shouldn't take too long.

**Comment by rborn** [comment]
@timotew great stuff, thanks a lot!

**Comment by timotew** [comment]
@rborn Thank you for taking your time to attend to this.

**Pull request merged**
